const fs = require("fs");

// input new word
const inputArray = [
  "pengolahan",
  "citra",
  "jaringan",
  "kecerdasan",
  "buatan",
  "sistem",
  "basis",
  "komputasi",
  "awan",
  "big",
  "internet",
  "of",
  "things",
  "keamanan",
  "mining",
  "analisis",
  "informasi",
  "pemrosesan",
  "paralel",
  "komunikasi",
  "pengenalan",
  "pola",
  "desain",
  "antarmuka",
  "pengguna",
  "kuantum",
  "sensor",
  "nirkabel",
  "visi",
  "cerdas",
  "robotika",
  "suara",
  "pakar",
  "proyek",
  "riset",
  "operasional",
  "simulasi",
  "berorientasi",
  "web",
  "manajemen",
  "pengetahuan",
  "pemantauan",
  "blockchain",
  "distribusi",
  "analisis",
  "virtualisasi",
  "bergerak",
  "pintar",
  "terdistribusi",
  "perdagangan",
  "elektronik",
  "uud",
  "enterprise",
  "penyimpanan",
  "geografis",
  "sig",
  "integrasi",
  "ketersediaan",
  "resiko",
  "aset",
  "arsitektur",
  "transaksi",
  "hci",
  "pengoptimalan",
  "layanan",
  "bioinspiratif",
  "sinyal",
  "variabilitas",
  "hipotesis",
  "signifikansi",
  "signifikan",
  "sampel",
  "populasi",
  "riset",
  "statistik",
  "korelasi",
  "regresi",
  "validitas",
  "eksperimen",
  "pengaruh",
  "kesimpulan",
  "diskusi",
  "teori",
  "framework",
  "konsep",
  "paradigma",
  "faktor",
  "skala",
  "interval",
  "normalitas",
  "pengukuran",
  "prose",
  "kausalitas",
  "pengendalian",
  "pemodelan",
  "pengamatan",
  "inovasi",
  "asumsi",
  "aspek",
  "kontribusi",
  "keterbatasan",
  "sistematis",
  "berkelanjutan",
  "pertumbuhan",
  "proyeksi",
  "pendekatan",
  "komparatif",
  "kesetaraan",
  "linear",
  "efisiensi",
  "perbandingan",
  "pemetaan",
  "keseimbangan",
  "motivasi",
  "orientasi",
  "konseptual",
  "koefisien",
  "rasio",
  "normal",
  "strategi",
  "efek",
  "kepuasan",
  "aspek-aspek",
  "partisipasi",
  "kinerja",
  "realitas",
  "sosial",
  "sumber",
  "daya",
];

const combineArray = [...inputArray, ...require("./kamus/kamus")].sort((a, b) => a.localeCompare(b));

const inputArrayUnique = [...new Set(combineArray)];

const kamusJson = JSON.stringify(inputArrayUnique, null, 2);

fs.writeFileSync("inputKamus.js", `module.exports = ${kamusJson}`, "utf-8");

setTimeout(() => {
  fs.writeFileSync("kamus/kamus.js", `module.exports = ${kamusJson}`, "utf-8");

  console.log("success...");
}, 2000);
